# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: edge.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'edge.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\nedge.proto\".\n\x0cImageRequest\x12\r\n\x05image\x18\x01 \x01(\x0c\x12\x0f\n\x07req_num\x18\x02 \x01(\x05\"/\n\rImageResponse\x12\r\n\x05\x65\x64ges\x18\x01 \x01(\x0c\x12\x0f\n\x07latency\x18\x02 \x01(\x01\x32;\n\x0b\x45\x64geService\x12,\n\x0b\x44\x65tectEdges\x12\r.ImageRequest\x1a\x0e.ImageResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'edge_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_IMAGEREQUEST']._serialized_start=14
  _globals['_IMAGEREQUEST']._serialized_end=60
  _globals['_IMAGERESPONSE']._serialized_start=62
  _globals['_IMAGERESPONSE']._serialized_end=109
  _globals['_EDGESERVICE']._serialized_start=111
  _globals['_EDGESERVICE']._serialized_end=170
# @@protoc_insertion_point(module_scope)
